### ISSUE TITLE
Command for adding reaction roles to specified messages

### ISSUE THREAD

**Issue by PKlempe** [PKlempe/SAM#18]
A command which adds so called reaction roles to a message posted by the bot. By clicking on one of the reactions, a specified role will be given to the user.

**Comment by SebastiantheAstorian** [comment]
How exactly should the command be used?
Like you use the command and the bot does create the message and adds the reactions?
And how does he know which reaction belongs to which roles?
We will also need a command to associate the roles with the reactions, and specify which ones the message must contain right?

**Comment by PKlempe** [comment]
Simple command with message id, emoji and role name as parameters. This association could then be saved in our database.
Example: `!rr 1238901239812 :green_apple: Noobs`

This way the same emojis can be used for multiple messages on our server while assigning different roles.
