### ISSUE TITLE
serverinfo embed shows the old server boost level limit

### ISSUE THREAD

**Issue by R3TRO04** [PKlempe/SAM#223]
![image](https://user-images.githubusercontent.com/24659399/134991047-d58c24c6-56d2-4670-bd8b-fd3d3aafb614.png)
# Description # 
As you can see in the `attachment`, the embed shows the correct level, but the old level limits are still set.
-------------
# How to reproduce # 
call `!serverinfo` in any textchannel.
-------------
# Solution  # 
set a new limit for the boost level in the `!serverinfo` command.
-------------

**Comment by abbcccddddeeeeeffffff** [comment]
"Server Features" also doesn't have a nice text for "ROLE_ICONS" and "NEW_THREAD_PERMISSIONS"
