### ISSUE TITLE
Changing the status of a modmail to "Done" removes attachments

### ISSUE THREAD

**Issue by PKlempe** [PKlempe/SAM#229]
If we receive a modmail with an image attached, said image gets removed as soon as the status is being changed to "Done".

**Comment by Katakompe** [comment]
Can't reproduce, attached files are not removed, even live, this worked fine. 
Do you have further details on how to reproduce this?

**Comment by PKlempe** [comment]
I tried to reproduce it myself and did not succeed too... So yeah... Maybe this was some bug related to `discord.py` or Discord itself and has now been fixed?

Anyway, I'm closing this issue.
