### ISSUE TITLE
Create and design database for stateful configuration

### ISSUE THREAD

**Issue by SebastiantheAstorian** [PKlempe/SAM#23]
We will need a database access for many operations which require configuration, like commands that should make the bot do something in a special channel or let the bot send a specific message repeatedly. Things like the message or the channel for the specific command need to be persisted so the bot wont forget them once configured. 

This issue is only about creating a database with a fitting (and extendable) design for this and creating code to access it correctly.

**Comment by PKlempe** [comment]
Should be pretty simple. Nearly everything we need is already provided by Discord. We simply need to create some tables for messages (e.g. welcome message), reaction roles, warnings and all that stuff.
