### ISSUE TITLE
Command for exchanging groups during the beginning of a semester

### ISSUE THREAD

**Issue by PKlempe** [PKlempe/SAM#56]
A dedicated text channel where users can exchange their assigned groups via a bot command. This could be combined with #41 so that only SAMs messages remain in the channel and therefore keeping it clear.

After a user has made an offer, an embeded message should be posted which contains every relevant information for an exchange (e.g. user, course, group, etc).
SAM should also be able to inform users via DM about possible exchange partners. Users should also be able to revoke their offer if they've successfully changed groups or simply changed their mind.

**Comment by SebastiantheAstorian** [comment]
Concluded features: 

- Fixed dates (as constants) where a cleanup job runs that deletes all db entries with according messages and that hides the channel (@ everyone nachrichten lesen)
- Wenn User angebot postet, bekommt er Nachricht mit liste aller passenden angebote und alle passenden angebots-user bekommen nachricht über neues angebot.
- Subbefehl zum löschen des Eintrags für einen User
